const items = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.number-2-pencil.com%2Fwp-content%2Fuploads%2F2020%2F10%2FButtermilk-Pancakes-4.jpg&f=1&nofb=1",
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcrummbs.co.uk%2Fwp-content%2Fuploads%2F2016%2F10%2FDiner-Double-Diablo-Burger-PWF-0085.jpg&f=1&nofb=1',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpreview.redd.it%2Fn3x0moarm0l11.jpg%3Fauto%3Dwebp%26s%3D2d75266c2d2e22449414aa006732d7fffa189ee6&f=1&nofb=1',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fres.cloudinary.com%2Fswiggy%2Fimage%2Fupload%2Ffl_lossy%2Cf_auto%2Cq_auto%2Fcl4nbhtzavj6nw8s3i1d&f=1&nofb=1',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.ctfassets.net%2F3s5io6mnxfqz%2F6rJkcdOdXfSuhnsJxeVoaq%2F9edffc622fac83f6656a7982e4501cb0%2FAdobeStock_88811376.jpeg&f=1&nofb=1',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fhips.hearstapps.com%2Fhmg-prod.s3.amazonaws.com%2Fimages%2Fsns-fb-ig-ad-oreo-1080x1080-14-1-1566573506.png%3Fresize%3D980%3A*&f=1&nofb=1',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages2.minutemediacdn.com%2Fimage%2Fupload%2Fc_fill%2Cg_auto%2Ch_1248%2Cw_2220%2Fv1555301966%2Fshape%2Fmentalfloss%2Fistock_34858640_small.jpg%3Fitok%3DuJQZQ2x2&f=1&nofb=1',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.stroke.org%2F-%2Fmedia%2Faha%2Frecipe%2Frecipe-images%2Fclassic-margherita-pizza-with-whole-wheat-pizza-crust.jpg%3Fh%3D684%26la%3Den%26mw%3D890%26w%3D890%26hash%3DCFAC93130C89F7838A5DEABD0B640BA48F25C67A&f=1&nofb=1',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstacumbrella.files.wordpress.com%2F2020%2F05%2Fimgpsh_fullsize_anim-40.jpg%3Fw%3D1024&f=1&nofb=1',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default items;